### ISSUE TITLE
Version requirements

### ISSUE THREAD

**Issue by nayha-auradkar** [oriern/SuperPAL#1]
Hello! I'm trying to use your SuperPAL code, but I have been running into several issues with versions. I installed everything in the requirements.txt file, but this file only contains the versions for transformers and allennlp. There are many more libraries that I have installed that have version incompatibilities with other libraries and the SuperPAL code. 

**Would you be able to provide a more details requirements.txt file?** I have been working on this for the past week and have not been able to run your code. Here are my current versions:
torchaudio==0.10.1+cu102
torchvision==0.11.2+cu102
torch==1.10.1+cu102
python==3.6.15
transformers==2.5.1
allennlp==0.9.0

**Comment by oriern** [comment]
Hi,
I am sorry for your time about this issue
These are the packages I have.
Does it solve the problem?

torch=1.1.0
torchvision=0.5.0

**Comment by oriern** [comment]
I have added an updated yaml file that solves the problem.
